name: flutter_map_location_marker
description: A flutter map plugin for displaying device current location.
version: 8.0.0-dev.1
repository: https://github.com/tlserver/flutter_map_location_marker
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_compass: ^0.7.0
  flutter_map: ^6.0.0-dev.2
  geolocator: ^9.0.2
  latlong2: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.1.2

dependency_overrides:
  flutter_map:
    git:
      url: https://github.com/fleaflet/flutter_map.git

flutter:
